---
###########################################
# 
# Common role block
#
# Preliminary common configs
#
#my_os : { Ubuntu : "ubuntu" , Debian : "debian" }
#listAptRepos : # It cames inside roles/Docker/default/main.yml 
#  - {
#       state   : "present" ,
#       keyUrl  : "https://download.docker.com/linux/{{ my_os[ansible_facts['distribution']] }}/gpg" ,
#       repoStr : "deb [arch=amd64] https://download.docker.com/linux/{{ my_os[ansible_facts['distribution']] }} {{ ansible_facts['distribution_release'] }} stable" ,
#       keyId   : "0EBFCD88" ,
#    }

# Some very early pip python packs (It's inside roles/Docker/default/main.yml)
#pip_install_list        : [ "docker" ]

#--- End of common role block

###########################################
#
# General var definition block - to all roles
#
# Our web server definitions
#
www_basedir             : "/var/www"
#www_htmldir             : "{{ www_basedir }}/html"
www_username            : "www-data"
web_service             : "nginx"

# Some Docker definitions
dockername_php          : "php"
dockername_nginx        : "nginx"
dockername_nginx2       : "nginx2"
dockername_mysql        : "db1"
# And inside Docker system
nginx_etc		: "/var/lib/docker/volumes/nginx_etc/_data"  	# Equivalent to /etc/nginx
nginx_html		: "/var/www/html" 	                        # Equivalent to /var/www/html
php_etc			: "/var/lib/docker/volumes/php_etc/_data"	# Equivalent to /etc/php
www_htmldir             : "{{ nginx_html }}"			        # Equivalent to /var/www/html

# For git to download/pull/clone the PHP small site example
#
domain1_rootdir         : "{{ www_htmldir }}/Orm_site"
domain1_docker_rootdir  : "/var/www/html/Orm_site"
git_data_dir		: "/var/git"
git_separate_dir	: "{{ git_data_dir }}/Orm_site.git"
sys_username		: "azureuser"
github_source_repo	: "https://github.com/lrgc01/Orm_test.git"
git_branch		: "stable"
#

#
# Will be used mainly with SSL certificate role
#
domain1                 : "{{ inventory_hostname }}"
#key_base_path           : "/etc/ssl/private"
#cert_base_path          : "/etc/ssl/certs"
key_base_path           : "{{ nginx_etc }}/ssl"
cert_base_path          : "{{ nginx_etc }}/ssl"
cert_name_prefix        : "selfsigned"
account_key             : "account-key.key"
#cert_name_prefix        : "stg-letsencrypt"
#account_key             : "stg-letsencrypt-account-key.key"
##cert_name_prefix        : "pro-{{ domain1 }}"
##account_key             : "pro-letsencrypt-account-key.key"
#
#

# These below are used with remote ansible python script and once installed it's better not remove them
base_dep_pkg_list:
   - { pkg : "python-mysqldb"  }
   - { pkg : "python-openssl"  }

#--- End of General vars block

###########################################
#
# Base role block variable definition
#
# General package and service hash list
#
# If a packet has a service associate it should be listed with srv, state and enabled.
# enabled and state defaults to true and started respectively.
dep_pkg_list		:
   - { pkg : "docker-ce" ,  srv : "docker" , state : "started" , enabled : true }
   - { pkg : "docker-ce-cli"   }
   - { pkg : "containerd.io"   }


#
# Some INI file configuration (php mainly, but may be others)
#
# Have to change for docker: after container creation...
#
#ini_file_list           :
#   - { path : "{{ php_etc }}/7.0/fpm/php.ini" , section : "PHP" , option : "allow_url_fopen" , value : "Off"  , docker : "{{ dockername_php }}" }
#   - { path : "{{ php_etc }}/7.0/fpm/php.ini" , section : "PHP" , option : "memory_limit"    , value : "128M" , docker : "{{ dockername_php }}" }

cron_list		:
- { name: "Update {{ domain1_rootdir }}" , minute: "*/5" , job: "git --git-dir={{ git_separate_dir }} --work-tree={{ domain1_rootdir }} pull --quiet"  , user: "{{ sys_username }}" , state: "present" }

# List of tar/zip balls to unarchive to specific places.
# Must define what it creates to be idempotent.
#unarchive_list  :
#   - {
#        src         : "https://github.com/lrgc01/Orm_test/archive/master.zip" ,
#        dest        : "{{ www_htmldir }}" ,
#        creates     : "{{ www_htmldir }}/README.md" ,
#        owner       : "root" ,
#        group       : "root" ,
#        remote_src  : true
#     }

#--- End of base role block

###########################################
#
# "users"'s role block
#
# Authorized_keys to fullfill in the server
#auth_keys_file_list     :
#   - { username : "azureuser"      , pub_key_file : "conf.d/testkey" }

#--- End of user stuff role block

###########################################
#
# gitcfg role
#
gitCloneList	:
   - {
	repo : "{{ github_source_repo }}" ,
        dest : "{{ domain1_rootdir }}" ,
        gitDir : "{{ git_separate_dir }}" ,
        update_y_n : false ,
        clone_y_n : true,
        branch : "{{ git_branch }}" ,
     }
        
###########################################
#
# SSLcrt role block variable definition
#
# SSL certificate and private key
#
# Production directory in Let's Encrypt: "https://acme-v02.api.letsencrypt.org/directory",
# Staging directory in Let's Encrypt: "https://acme-staging-v02.api.letsencrypt.org/directory",
#
# Due to map filter inside the loop, cert_hash_list first element cannot be false like other lists
# So we define another parameter to allow the system to run safely (cert_hash_list[*].enabled)
cert_hash_list		:
   -  {
        enabled			: true ,
        selfsigned		: true ,
        pem_file                : false ,
        account_priv_key_path	: "{{ key_base_path }}/{{ account_key }}",
        csr_priv_key_path	: "{{ key_base_path }}/{{ cert_name_prefix }}-csr-key.key",
        csr_cert_path		: "{{ cert_base_path }}/{{ cert_name_prefix }}.csr",
        crt_cert_path		: "{{ cert_base_path }}/{{ cert_name_prefix }}.crt",
        crt_fullchain_path	: "{{ cert_base_path }}/{{ cert_name_prefix }}-fullchain.crt",
        crt_interchain_path	: "{{ cert_base_path }}/{{ cert_name_prefix }}-intermmediate.crt",
        acme_directory		: "https://acme-staging-v02.api.letsencrypt.org/directory",
        C			: "CA",
        ST			: "Quebec",
        L			: "Montreal",
        O			: "Lrgc01 private site",
        OU			: "Lrgc01 private site",
        email_address		: "luizrogeriocarvalho@gmail.com",
        CN			: "{{ domain1 }}",
        force_cert_y_n		: "no",
        allow_creation_y_n	: "yes",
        remaining_days		: "30",
        server_certkey_path	: "{{ key_base_path }}/{{ domain1 }}.key",
        server_cert_path	: "{{ cert_base_path }}/{{ domain1 }}.crt",
        local_certkey_path	: "{{ confdir }}/{{ domain1 }}.key",
        local_cert_path		: "{{ confdir }}/{{ domain1 }}.crt",
        web_rootdir		: "{{ domain1_rootdir }}"
      }
# Below other variables depend on the cert_hash_list above.
# In a near future this list maybe mapped from the cert_hash_list in runtime
server_cert_n_key_list	:
   -  { 
        src  : "{{ cert_hash_list[0].csr_priv_key_path }}",
        dest : "{{ cert_hash_list[0].server_certkey_path }}"
      }
   -  { 
        src  : "{{ cert_hash_list[0].crt_cert_path }}",
        dest : "{{ cert_hash_list[0].server_cert_path }}"
      }
# srv defines if a service will be restarted upon modification in file upload
# In a near future this list maybe mapped from the cert_hash_list in runtime
ssl_up_down_files_list 	:
   -  { 
        local  : "{{ cert_hash_list[0].local_certkey_path }}",
        remote : "{{ cert_hash_list[0].server_certkey_path }}",
        action : [ "upload" , "download" ],
        srv    : "{{ web_service }}"
      }
   -  { 
        local  : "{{ cert_hash_list[0].local_cert_path }}" ,
        remote : "{{ cert_hash_list[0].server_cert_path }}",
        action : [ "upload" , "download" ],
        srv    : "{{ web_service }}"
      }

#--- End of SSLCrt role block

#
# "finals"'s role block
#
later_dirs_config_list       :
   - { enabled : true , path : "{{ git_data_dir }}"    , owner: "{{ sys_username }}" , group : "{{ sys_username }}" , mode : "u+rw,a+rX" , recurse : true , }
   - { enabled : true , path : "{{ domain1_rootdir }}" , owner: "{{ sys_username }}" , group : "{{ sys_username }}" , mode : "u+rw,a+rX" , recurse : true , }

#--- End of "finals" role block

###########################################
#
# Docker role block
#
#
# List of containers to be created.
# Except for 'name' and 'networks', all others may be omitted:
#    networks (for now networks must be defined - or use 'bridge')
#    links
#    volumes
#    volumes_from
#    working_dir
#    user
#    published_ports
#    state
#    purge_networks (must use name=bridge when removing others)
#    pull = check image to pull always the newer
#
# All plural variable names are LISTs, but 'networks'
# must be a list of dict.
# If omitted, 'image' will default to container's name.
#
dockerContainerList :
  - {
        enabled         : false ,
        name            : "maven" ,
        image           : "lrgc01/scratch_maven" ,
        networks        : [ { name : "bridge" } ] ,
        volumes         : [ "maven:/opt/maven" , ] ,
        state           : "present" ,
    }
  - {
        enabled         : false ,
        name            : "jenkins" ,
        image           : "lrgc01/jenkins" ,
        pull            : true ,
        networks        : [ { name : "jenkins_net" } ] ,
        volumes         : [ "jenkins:/var/lib/jenkins" , "/home:/home", ] ,
        volumes_from    : [ "maven" ] ,
        working_dir     : "/var/lib/jenkins" ,
        user            : "jenkins" ,
        published_ports : [ "0.0.0.0:8080:8080" ] , 
        state           : "started" ,
    }
  - {
        enabled         : false ,
        name            : "python" ,
        image           : "lrgc01/pytest_pyinstaller" ,
        pull            : true ,
        networks        : [ { name : "jenkins_net" } ] ,
        volumes         : [ "/home:/home", ] ,
        volumes_from    : [ "jenkins" ] ,
        state           : "started" ,
    }
  - {
        enabled         : false ,
        name            : "nodejs" ,
        image           : "lrgc01/nodejs" ,
        pull            : true ,
        networks        : [ { name : "jenkins_net" } ] ,
        volumes         : [ "/home:/home", ] ,
        volumes_from    : [ "jenkins" ] ,
        published_ports : [ "0.0.0.0:3030:3000" ] , 
        state           : "started" ,
    }
  - {
        enabled         : true ,
        name            : "{{ dockername_php }}" ,
        image           : "lrgc01/php-stretch_slim" ,
        pull            : true ,
        networks        : [ { name : "nginx_net" } ] ,
        volumes         : [ "php_etc:/etc/php", "php_run:/run/php", "/var/www/html:/var/www/html" , ] ,
        published_ports : [ "0.0.0.0:9900:9000", ] , 
        state           : "started" ,
    }
  - {
        enabled         : true ,
        name            : "{{ dockername_nginx }}" ,
        image           : "lrgc01/nginx-stretch_slim" ,
        pull            : true ,
        networks        : [ { name : "nginx_net" } ] ,
        volumes         : [ "nginx_etc:/etc/nginx", "nginx_log:/var/log/nginx", ] ,
        volumes_from    : [ "php" ] ,
        published_ports : [ "0.0.0.0:8800:80", "0.0.0.0:4433:443", ] , 
        state           : "started" ,
    }
  - {
        enabled         : true ,
        name            : "{{ dockername_nginx2 }}" ,
        image           : "lrgc01/nginx-stretch_slim" ,
        pull            : true ,
        networks        : [ { name : "nginx_net" } ] ,
        #volumes         : [ "nginx_etc:/etc/nginx", "nginx_log:/var/log/nginx", ] ,
        volumes_from    : [ "php" , "{{ dockername_nginx }}" ] ,
        published_ports : [ "0.0.0.0:8880:80", "0.0.0.0:4443:443", ] , 
        state           : "started" ,
    }
  - {
        enabled         : true ,
        name            : "{{ dockername_mysql }}" ,
        image           : "lrgc01/mariadb-server-debian9" ,
        pull            : true ,
        networks        : [ { name : "bridge" } ] ,
        volumes         : [ "mysql_data:/var/lib/mysql", "mysql_etc:/etc/mysql", ] ,
        published_ports : [ "0.0.0.0:3306:3306", ] , 
        state           : "started" ,
    }

# After container creation:
#
# dir, file, template or link, depending on key values
#
# Will be used in template and file modules to create, delete and link.
#
# This docker_dir_file_tmpl_list dict var will be used in 4 different tasks, one of 
# each type: tmpl, dir, link and file.
#
# If mode not present, it will default to 0644
# Note that one line may be used to multiple goals as defined in types.
# "dir" uses dest only
# "link" uses src and dest: ln -s src dest (force=yes => ln -s -f)
# "tmpl" uses name and dest: name.j2 -> dest/name
# "absent" uses dest to remove files
# srv is used to restart the service, if applicable, after a template is changed.
docker_dir_file_tmpl_list     :
   - { types : [ "dir" ]      , dest : "{{ nginx_etc }}/ssl"                   }
   - { types : [ "tmpl" ]     , dest : "{{ nginx_etc }}/sites-available" , tmpl : "nginx-default.j2"   , name : "nginx-default" }
   - { types : [ "tmpl" ]     , dest : "{{ nginx_etc }}/sites-available" , tmpl : "nginx_dom1-docker.conf.j2" , name : "{{ domain1 }}.conf" , docker : "{{ dockername_nginx }}" }
   - { types : [ "tmpl" ]     , dest : "{{ nginx_etc }}/snippets"        , tmpl : "nginx_dom1-docker-cert.conf.j2" , name : "{{ domain1 }}-cert.conf"  , docker : "{{ dockername_nginx }}" }
   - { types : [ "link" ]     , src  : "/etc/nginx/sites-available/{{ domain1 }}.conf" , dest : "{{ nginx_etc }}/sites-enabled/{{ domain1 }}.conf" , force : "yes" , follow : "no" }
   - { types : [ "absent" ]   , dest : "{{ nginx_etc }}/sites-enabled/default" }
   - { types : [ "absent" ]   , dest : "{{ nginx_etc }}/sites-enabled/nginx-default" }
#   - { types : [ "dir" ]      , dest : "{{ git_data_dir }}"                    }
#   - { types : [ "absent" ]       , dest : "{{ www_htmldir }}/README.md" }

# Define local and remote files both for upload (copy)
# and download (fetch).
# Action is mandatory (same idea of types in dir_file_tmpl_list above).
# action = list of upload or download or both
# DON'T forget to have local files to upload to the server and local dirs when downloading
docker_up_down_files_list :
   -  { 
        local  : "{{ cert_hash_list[0].local_certkey_path }}",
        remote : "{{ cert_hash_list[0].server_certkey_path }}",
        action : [ "upload" ]
      }
   -  { 
        local  : "{{ cert_hash_list[0].local_cert_path }}" ,
        remote : "{{ cert_hash_list[0].server_cert_path }}",
        action : [ "upload" ]
      }

#
#--- End of Docker role block
