---
- name: Create / change Resource Group(s)--------------------
  azure_rm_resourcegroup:
     subscription_id: "{{ azureSPList.subscription_id }}"
     client_id: "{{ azureSPList.appId }}"
     secret: "{{ azureSPList.password }}"
     tenant: "{{ azureSPList.tenant }}"
     cert_validation_mode: "{{ cert_validation_mode | default(omit) }}"
     name: "{{ item.name }}"
     location: "{{ item.location }}"
     tags: "{{ item.tags | default(omit) }}"
     state: "{{ item.state | default(omit) }}"
     force: "{{ item.force | default(omit) }}"
  loop: "{{ az_RGList }}"
  when: az_RGList is defined
  register: resource_group_created
  tags: azure_vm, azure_subnet, azure_vnet, azure_rg

- name: Create / change virtual network(s)-------------------
  azure_rm_virtualnetwork:
     subscription_id: "{{ azureSPList.subscription_id }}"
     client_id: "{{ azureSPList.appId }}"
     secret: "{{ azureSPList.password }}"
     tenant: "{{ azureSPList.tenant }}"
     cert_validation_mode: "{{ cert_validation_mode | default(omit) }}"
     resource_group: "{{ item.rg }}"
     name: "{{ item.name }}"
     address_prefixes: "{{ item.addresses }}"
     state: "{{ item.state | default(omit) }}"
     tags: "{{ item.tags | default(omit) }}"
  loop: "{{ az_VNetList  }}"
  when: az_VNetList is defined and resource_group_created is success
  register: virtual_network_created
  tags: azure_vm, azure_subnet, azure_vnet

- name: Add / update subnet(s) ------------------------------
  azure_rm_subnet:
     subscription_id: "{{ azureSPList.subscription_id }}"
     client_id: "{{ azureSPList.appId }}"
     secret: "{{ azureSPList.password }}"
     tenant: "{{ azureSPList.tenant }}"
     cert_validation_mode: "{{ cert_validation_mode | default(omit) }}"
     resource_group: "{{ item.rg }}"
     name: "{{ item.name }}"
     address_prefix: "{{ item.address }}"
     virtual_network: "{{ item.VNetwork }}"
     state: "{{ item.state | default(omit) }}"
     tags: "{{ item.tags | default(omit) }}"
  loop: "{{ az_SubnetList  }}"
  when: az_SubnetList is defined and virtual_network_created is success
  register: sub_network_created
  tags: azure_vm, azure_subnet, azure_pub_ip

- name: Create / change Public IP(s) ------------------------
  azure_rm_publicipaddress:
     subscription_id: "{{ azureSPList.subscription_id }}"
     client_id: "{{ azureSPList.appId }}"
     secret: "{{ azureSPList.password }}"
     tenant: "{{ azureSPList.tenant }}"
     cert_validation_mode: "{{ cert_validation_mode | default(omit) }}"
     resource_group: "{{ item.rg }}"
     name: "{{ item.name }}"
     allocation_method: "{{ item.allocation_method | default(omit) }}"
     domain_name: "{{ item.domain_name | default(omit) }}"
     state: "{{ item.state | default(omit) }}"
  loop: "{{ az_PubIPList  }}"
  when: az_PubIPList is defined and sub_network_created is success
  register: public_ip_created
  tags: azure_vm, azure_pub_ip

- name: Create / modify Virtual Machine(s) ------------------
  azure_rm_virtualmachine:
     subscription_id: "{{ azureSPList.subscription_id }}"
     client_id: "{{ azureSPList.appId }}"
     secret: "{{ azureSPList.password }}"
     tenant: "{{ azureSPList.tenant }}"
     cert_validation_mode: "{{ cert_validation_mode | default(omit) }}"
     resource_group: "{{ item.rg }}"
     name: "{{ item.name }}"
     vm_size: "{{ item.vm_size }}"
     state: "{{ item.state | default(omit) }}"
     admin_username: "{{ item.admuser | default('azureuser') }}"
     ssh_password_enabled: "{{ item.ssh_pass | default(false) }}"
     ssh_public_keys: "{{ item.ssh_public_keys | default(omit) }}"
     tags: "{{ item.tags | default(omit) }}"
     os_type: "{{ item.os_type | default(omit) }}"
     image: "{{ item.image }}"
  loop: "{{ az_VMList  }}"
  when: az_VMList is defined and sub_network_created is success
  register: vm_created
  tags: azure_vm
