---
# After templates and/or if a local new certificate was created 
# (or changed), restart the web server (nginx).
- name: Restart web server 
  service:
    name: "{{ web_service }}"
    state: "restarted"
    enabled: true
  when: web_service is defined

- name: Restart other web or proxy server 
  service:
    name: "{{ web_service_other }}"
    state: "restarted"
    enabled: true
  when: web_service_other is defined

# Not used
- name: Restart dependencies services
  service: 
    name: "{{ item.srv }}" 
    state: "restarted" 
    enabled: true
  when: item.srv is defined
  loop: "{{ dep_pkg_list }}"
