---
- hosts: dockerMongoDB
  connection: local
  gather_facts: "{{ gather_y_n | default(true) }}"
  remote_user: "{{ remote_user | default('luiz') }}"
  become: true
  vars_files:
    - vars_files/dockerMongoDB.yml
  roles:
    - common
    - base
    - Docker
