---
- hosts: centosold
  gather_facts: "{{ gather_y_n | default(true) }}"
  remote_user: "{{ remote_sudo_user | default('luiz') }}"
  become: true
  roles:
    - common
    - base
    - users
#    - Docker
