---
# These servers might be kept in one server each 
# or joined into one or two servers according to 
# the project. Just change the inventory.
- hosts: dockerNginxPHPMariaDB
  gather_facts: "{{ gather_y_n }}"
  become: true
  remote_user: "luiz"
  roles:
    - common
    - base
    - users
    - Docker
    - gitcfg
    - phpcfg
    - finals

- hosts: HAservers
  gather_facts: "{{ gather_y_n }}"
  become: true
  remote_user: "luiz"
  roles:
   - common
   - base
   - users
   - SSLcrt

- hosts: DBservers
  gather_facts: "{{ gather_y_n }}"
  become: true
  remote_user: "luiz"
  roles:
   - common
   - base
   - users
   - DB_adm
   - restore
   - finals
