---
###########################################
#
# Docker role block
#
# Official repository to install docker in Debian
# Should be adapted to many other systems in the future
my_os : { Ubuntu : "ubuntu" , Debian : "debian" }
listAptRepos : 
  - {  
       state   : "present" ,
       keyUrl  : "https://download.docker.com/linux/{{ my_os[ansible_facts['distribution']] }}/gpg" ,
       repoStr : "deb [arch=amd64] https://download.docker.com/linux/{{ my_os[ansible_facts['distribution']] }} {{ ansible_facts['distribution_release'] }} stable" ,
       keyId   : "0EBFCD88" ,
    }

# Some very early pip python packs
pip_install_list        : [ "docker" ]

#
# List of containers to be created.
# Except for 'name' and 'networks', all others may be omitted:
#    networks (for now networks must be defined - or use 'bridge')
#    links
#    volumes
#    volumes_from
#    working_dir
#    user
#    published_ports
#    state
#    purge_networks (must use name=bridge when removing others)
#    pull = check image to pull always the newer
#
# All plural variable names are LISTs, but 'networks'
# must be a list of dict.
# If omitted, 'image' will default to container's name.
#
#dockerContainerList :
#  - {   
#        enabled         : true ,
#        name            : "maven" ,
#        image           : "lrgc01/scratch_maven" ,
#        networks        : [ { name : "bridge" } ] ,
#        volumes         : [ "maven:/opt/maven" , ] ,
#        state           : "present" ,
#    }

#
#--- End of Docker role block
