---
- name: Grant repodir permissions to git user -------------
  file:
    path: "{{ git_repodir }}"
    state: directory
    owner: "{{ git_user }}"
    group: "{{ git_user }}"
    mode: "g+rwx"
    recurse: false
  when: git_repodir is defined
  register: git_perms_in_repodir
  tags: git_config

- name: Create some git projects on server ----------------
  shell: "su - {{ git_user }} -c \"/usr/bin/git init --bare {{ git_repodir }}/{{ item }}\""
  args:
    creates: "{{ item }}"
    chdir: "{{ git_repodir }}"
    warn: false
  loop: "{{ git_project_list }}"
  when: git_project_list is defined 
        and git_repodir is defined 
        and git_perms_in_repodir is success 
  register: git_repos_created
  tags: git_config

- name: Clone a remote repo in a separate git dir ---------
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    separate_git_dir: "{{ item.gitDir }}"
    update: "{{ item.update_y_n | default(omit) }}"
    clone: "{{ item.clone_y_n | default(omit) }}"
    version: "{{ item.branch | default(omit) }}"
    ssh_opts: "{{ item.ssh_opts | default(omit) }}"
    accept_hostkey: "{{ item.accept_hostkey | default(true) }}"
    key_file: "{{ item.key_file | default(omit) }}"
  become: "{{ item.become | default(omit) }}"
  loop: "{{ gitCloneList }}"
  when: gitCloneList is defined
  register: git_repo_cloned
  tags: git_config, git_clone
