---
# Users example yml var file
#
# User administration
#
drupaladm_user          : "drupaladm"
siteadm_user            : "siteadm"
git_user		: "git"
# users to be created.
# A later task will retrieve these keys asked to be created in here:
users_list              :
   - false
   - { username : "{{ drupaladm_user }}" , comment : "Drupal admin user" , groups : "www-data" , sshkey: false }
   - { username : "{{ siteadm_user }}"   , comment : "Site admin user"   , groups : "www-data" , sshkey: false }
   - { username : "{{ git_user }}"       , comment : "Git user"          , groups : ""         , sshkey: true  }
auth_keys_file_list	:
   - false
   - { username : "{{ git_user }}"	, pub_key_file : "conf.d/luiz_pub_key"		}
   - { username : "{{ git_user }}"	, pub_key_file : "conf.d/luiz_newage1_pub_key"	}
