---
- name: Install dependency packages -----------------------
  apt: 
    pkg: "{{ item.pkg }}" 
    state: "present"
  loop: "{{ dep_pkg_list }}"
  when: dep_pkg_list[0]
  register: dep_pkg_installed
  tags: install_dep_pkg

- name: Ensure directories dir_file_tmpl_list.types=dir ---
  file: 
    path: "{{ item.dest }}" 
    state: "directory"
  loop: "{{ dir_file_tmpl_list }}"
  when: dir_file_tmpl_list[0] and "dir" in item.types
  register: directories_in_place
  tags: config_files, deploy_templates

- name: Remove undesired files (absent in item.types) -----
  file:
    path: "{{ item.dest }}"
    state: "absent"
  loop: "{{ dir_file_tmpl_list }}"
  when: dir_file_tmpl_list[0] and directories_in_place is success and "absent" in item.types
  register: removed_files
  tags: config_files, deploy_templates

- name: Deploy templates dir_file_tmpl_list.types=tmpl ----
  template:
    src: "{{ item.tmpl }}"
    dest: "{{ item.dest }}/{{ item.name }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ dir_file_tmpl_list }}"
  when: dir_file_tmpl_list[0] and directories_in_place is success and "tmpl" in item.types
  register: templates_in_place
  tags: config_files, deploy_templates

- name: Make proper links dir_file_tmpl_list.types=link ---
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: "{{ item.force | default('no') }}"
    follow: "{{ item.follow | default('no') }}"
  loop: "{{ dir_file_tmpl_list }}"
  when: dir_file_tmpl_list[0] and removed_files is success and templates_in_place is success and "link" in item.types
  register: links_in_place
  tags: config_files, deploy_templates

- name: Upload some files from a list when action=upload --
  copy:
    dest: "{{ item.remote }}"
    src: "{{ item.local }}"
  loop: "{{ up_down_files_list }}"
  when: up_down_files_list[0] and "upload" in item.action
  register: files_uploaded
  tags: config_files, copy_files

- name: Restart service after tmpl/file/link change -------
  service:
    name: "{{ item.item.srv }}"
    state: "restarted"    
    enabled: true
  loop: "{{ templates_in_place.results }} + {{ files_uploaded.results }}"
  when: (templates_in_place is changed or files_uploaded is changed) and item is changed and item.item.srv is defined
  tags: config_files, deploy_templates, copy_files

