---
- name: Drop all databases ------------------------------
  mysql_db:
    login_user: "{{ item.admuser }}"
    login_password: "{{ item.admpass }}"
    login_host: "{{ item.host }}"
    name: "{{ item.dbname }}"
    state: absent
  loop: "{{ db_list }}"
  when: db_list is defined and item.drop
  register: databases_dropped
  tags: drop_databases

- name: Uninstall packages dependencies -----------------
  apt: 
    pkg: "{{ item.pkg }}" 
    state: "absent"
    purge: "{{ purge_y_n }}" 
    autoremove: "{{ autoremove_y_n }}"
  loop: "{{ dep_pkg_list }}"
  when: dep_pkg_list[0]
  register: dep_pkg_uninstalled
  tags: uninstall_dep_pkg, remove_files_n_dirs

- name: Remove basic files and/or directories -----------
  file: 
    path: "{{ item }}"
    state: absent
  loop: "{{ base_file_dir_remove_list }}"
  when: base_file_dir_remove_list is defined 
  register: file_n_dir_removed
  tags: remove_files_n_dirs

# Remove other parts (check condition below)
- name: Purge later files and/or directories ------------
  file: 
    path: "{{ item }}"
    state: absent
  loop: "{{ file_dir_remove_list }}"
  when: purge_y_n == "true" and autoremove_y_n == "true" and dep_pkg_uninstalled is success
  register: file_n_dir_removed
  tags: remove_files_n_dirs

# untrust and unregister repositories
- name: Remove trusted added apt repositories -----------
  apt_repository:
    repo: "{{ item.repoStr }}"
    state: absent
  loop: "{{ listAptRepos }}"
  when: listAptRepos[0] and item.state and item.repoStr
  register: rem_apt_repos_done
  tags: remove_repository

# remove apt keys
- name: Remove apt repo keys from apt configuration -----
  apt_key:
    url: "{{ item.keyUrl }}"
    state: absent
    id: "{{ item.keyId }}"
  loop: "{{ listAptRepos }}"
  when: listAptRepos[0] and item.state and item.keyUrl and rem_apt_repos_done is success
  register: rem_apt_keys_done
  tags: remove_repository, remove_apt_keys
