---
# Should be used only locally: e.g.: aws stuff
- name: Preliminary dependency install -- python-pip ------
  apt: 
    pkg: "python-pip"
    state: "present"
  tags: python_bootstrap

- name: Install local python dependencies via pip ---------
  pip:
    name: "{{ item }}"
  loop: "{{ pip_install_list }}"
  when: pip_install_list[0]
  tags: python_bootstrap

