# Two step challenge to create CRT cert
- name: Create certificate - 1st step challenge -----------
  acme_certificate:
    account_key_src: "{{ item.account_priv_key_path }}"
    acme_version: '2'
    acme_directory: "{{ item.acme_directory }}"
    modify_account: "no"
    csr: "{{ item.csr_cert_path }}"
    dest: "{{ item.crt_cert_path }}"
    fullchain_dest: "{{ item.crt_fullchain_path }}"
    force: "{{ item.force_cert_y_n }}"
    remaining_days: "{{ item.remaining_days }}"
  loop: "{{ cert_hash_list }}"
  when: private_key_created is success and csr_cert_created is success 
        and cert_hash_list is defined and item.enabled
        and not item.selfsigned 
  register: cert_challenge_first
  tags: ssl_certificate

- name: Create directory structure for challenge ----------
  file:
    state: "directory"
    path: "{{ item.item.web_rootdir }}/{{ item['challenge_data'][item.item.CN]['http-01']['resource'] | dirname }}"
  loop: "{{ cert_challenge_first.results }}"
  when: cert_challenge_first is changed and item is changed
  register: cert_challenge_dir_created
  tags: ssl_certificate
  
- name: Copy resource to web site to complete the 2nd step  
  copy:
    dest: "{{ item.item.web_rootdir }}/{{ item['challenge_data'][item.item.CN]['http-01']['resource'] }}"
    content: "{{ item['challenge_data'][item.item.CN]['http-01']['resource_value'] }}"
  loop: "{{ cert_challenge_first.results }}"
  when: cert_challenge_first is changed and item is changed and cert_challenge_dir_created is success
  register: cert_challenge_in_place
  tags: ssl_certificate

- name: Create certificate - 2nd step challenge -get certs-
  acme_certificate:
    account_key_src: "{{ item.item.account_priv_key_path }}"
    acme_version: '2'
    acme_directory: "{{ item.item.acme_directory }}"
    modify_account: "no"
    csr: "{{ item.item.csr_cert_path }}"
    dest: "{{ item.item.crt_cert_path }}"
    fullchain_dest: "{{ item.item.crt_fullchain_path }}"
    chain_dest: "{{ item.item.crt_interchain_path }}"
    remaining_days: "{{ item.item.remaining_days }}"
    data: "{{ item }}"
  loop: "{{ cert_challenge_first.results }}"
  when: cert_challenge_first is changed and item is changed
  register: challenge_2nd_step_done
  tags: ssl_certificate
